### PR TITLE
Exclude CI files from the package

### PR DESCRIPTION
**Pull request by cuviper**

### CODE REVIEW

**Comment by Amanieu** [comment]
There really should be a Rust project template that deals with all this stuff...

**Comment by cuviper** [comment]
Yeah, it's annoying. And CI files aren't really a big deal, but I was requested to remove them in the Fedora [packaging review](https://bugzilla.redhat.com/show_bug.cgi?id=1666082#c2).

**Comment by Amanieu** [comment]
Thanks! Do you need me to publish a new version now?

**Comment by cuviper** [comment]
I already patched it in our build, so there's no rush. Thanks!

**Pull request merged**
